# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros2-qt-gui-cpp
  version: 2.7.6
source:
  git: https://github.com/ros2-gbp/qt_gui_core-release.git
  tag: release/jazzy/qt_gui_cpp/2.7.6-1
  target_directory: ros2-qt-gui-cpp/src/work
  patches:
    - patch/ros-jazzy-qt-gui-cpp.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 25
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://ros.org/wiki/qt_gui_cpp
  repository: https://github.com/ros-visualization/qt_gui_core
  license: BSD-3-Clause
  summary: qt_gui_cpp provides the foundation for C++-bindings for qt_gui and creates bindings for every generator available. At least one specific binding must be available in order to use C++-plugins.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: osx
      then:
        - clang-tools ${{ (cxx_compiler_version ~ '.*') if cxx_compiler_version is defined else '*' }}
    - ${{ 'pyqt' if (build_platform != target_platform) }}
    - ${{ 'qt-main' if (build_platform != target_platform) }}
    - if: build_platform != target_platform
      then:
        - qt-main
  host:
    - ${{ 'libgl-devel' if linux }}
    - ${{ 'libopengl-devel' if linux }}
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pep517
    - pip
    - pkg-config
    - pyqt-builder <1.20
    - pyside2
    - python
    - qt-main
    - ros2-ament-cmake
    - ros2-ament-cmake-pytest
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-pluginlib
    - ros2-python-qt-binding
    - ros2-ros-environment
    - ros2-ros-workspace
    - ros2-tinyxml2-vendor
    - sip <6.16
  run:
    - pep517
    - pyqt-builder <1.20
    - python
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-pluginlib
    - ros2-qt-gui
    - ros2-ros-workspace
    - ros2-tinyxml2-vendor
