# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-moveit-core
  version: 2.12.4
source:
  git: https://github.com/ros2-gbp/moveit2-release.git
  tag: release/jazzy/moveit_core/2.12.4-1
  target_directory: ros-jazzy-moveit-core/src/work
  patches:
    - patch/ros-jazzy-moveit-core.patch
    - patch/ros-jazzy-moveit-core.win.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://moveit.ros.org
  repository: https://github.com/moveit/moveit2
  license: BSD-3-Clause
  summary: Core libraries used by MoveIt
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - assimp
    - if: build_platform == target_platform
      then:
        - pkg-config
    - bullet
    - eigen
    - fcl
    - libboost-devel
    - libboost-python-devel
    - numpy
    - pip
    - pkg-config
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gmock
    - ros-jazzy-ament-cmake-google-benchmark
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-index-cpp
    - ros-jazzy-angles
    - ros-jazzy-common-interfaces
    - ros-jazzy-eigen-stl-containers
    - ros-jazzy-eigen3-cmake-module
    - ros-jazzy-generate-parameter-library
    - ros-jazzy-geometric-shapes
    - ros-jazzy-geometry-msgs
    - ros-jazzy-google-benchmark-vendor
    - ros-jazzy-kdl-parser
    - ros-jazzy-launch-testing-ament-cmake
    - ros-jazzy-moveit-common
    - ros-jazzy-moveit-msgs
    - ros-jazzy-moveit-resources-panda-moveit-config
    - ros-jazzy-moveit-resources-pr2-description
    - ros-jazzy-octomap-msgs
    - ros-jazzy-orocos-kdl-vendor
    - ros-jazzy-osqp-vendor
    - ros-jazzy-pluginlib
    - ros-jazzy-random-numbers
    - ros-jazzy-rcl-interfaces
    - ros-jazzy-rclcpp
    - ros-jazzy-rclpy
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-rsl
    - ros-jazzy-ruckig
    - ros-jazzy-sensor-msgs
    - ros-jazzy-shape-msgs
    - ros-jazzy-srdfdom
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-eigen
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-kdl
    - ros-jazzy-trajectory-msgs
    - ros-jazzy-urdf
    - ros-jazzy-urdfdom
    - ros-jazzy-urdfdom-headers
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - assimp
    - bullet
    - eigen
    - fcl
    - libboost-devel
    - libboost-python-devel
    - python
    - ros-jazzy-angles
    - ros-jazzy-common-interfaces
    - ros-jazzy-eigen-stl-containers
    - ros-jazzy-eigen3-cmake-module
    - ros-jazzy-generate-parameter-library
    - ros-jazzy-geometric-shapes
    - ros-jazzy-geometry-msgs
    - ros-jazzy-google-benchmark-vendor
    - ros-jazzy-kdl-parser
    - ros-jazzy-moveit-common
    - ros-jazzy-moveit-msgs
    - ros-jazzy-octomap-msgs
    - ros-jazzy-osqp-vendor
    - ros-jazzy-pluginlib
    - ros-jazzy-random-numbers
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-workspace
    - ros-jazzy-rsl
    - ros-jazzy-ruckig
    - ros-jazzy-sensor-msgs
    - ros-jazzy-shape-msgs
    - ros-jazzy-srdfdom
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-eigen
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-kdl
    - ros-jazzy-trajectory-msgs
    - ros-jazzy-urdf
    - ros-jazzy-urdfdom
    - ros-jazzy-urdfdom-headers
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
