# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-pcl-conversions
  version: 2.6.2
source:
  git: https://github.com/ros2-gbp/perception_pcl-release.git
  tag: release/jazzy/pcl_conversions/2.6.2-1
  target_directory: ros-jazzy-pcl-conversions/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://wiki.ros.org/pcl_conversions
  repository: https://github.com/ros-perception/perception_pcl
  license: BSD-3-Clause
  summary: Provides conversions from PCL data types and ROS message types
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - ${{ 'libgl-devel' if linux }}
    - ${{ 'libopengl-devel' if linux }}
    - if: build_platform == target_platform
      then:
        - pkg-config
    - eigen
    - libboost-devel
    - numpy
    - pcl
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-message-filters
    - ros-jazzy-pcl-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - vtk-base
  run:
    - eigen
    - libboost-devel
    - pcl
    - python
    - ros-jazzy-message-filters
    - ros-jazzy-pcl-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-workspace
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - vtk-base
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
tests:
  - script:
      - ros2 pkg prefix pcl_conversions
    requirements:
      run:
        - ros-jazzy-ros2pkg
