numpy:
  - 2

assimp:
  - 6
# Workaround for https://github.com/RoboStack/ros-jazzy/pull/40#issuecomment-2782226697
cmake:
  - 3.*
eigen_abi_devel:
  - '5.0.1'
icu:
  # icu78 migration is nearly complete on conda-forge.
  - '78'
# Apply conda-forge's mostly-complete 2026 Q2 Abseil/gRPC/Protobuf migration.
libabseil:
  - 20260526
libgrpc:
  - '1.82'
libprotobuf:
  - 7.35.1
protobuf:
  - 7.35.1
fmt:
  - '12.1'
graphviz:
  - '14'
jsoncpp:
  # jsoncpp 1.9.8 migration is nearly complete on conda-forge.
  - 1.9.8
libopencv:
  - 4.13.0
libmujoco:
  - 3.10.0
# Mitigation for
# https://github.com/RoboStack/ros-jazzy/pull/126#issuecomment-3515455380
libcap:
  - 2.78
libhwloc:
  - 2.13.0
libxml2:
  - '2.14'
libzenohc:
  - 1.9.0
libzenohcxx:
  - 1.9.0
lua:
  - 5.4
pugixml:
  - '1.15'
shaderc:
  - '2026.3'
spdlog:
  - 1.17
tbb:
  - '2023'
tbb_devel:
  - '2023'
urdfdom:
  - '6.0'
urdfdom_headers:
  - '3.0'
vtk:
  - 9.6.2


cdt_name:  # [linux]
  - conda  # [linux]

python:
  - 3.12.* *_cpython
python_impl:
  - cpython

c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2022                     # [win]
c_compiler_version:            # [unix]
  - 14                         # [linux]
  - 19                         # [osx]
c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 12.0                       # [osx and x86_64]
  - 12.0                       # [osx and arm64]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2022                     # [win]
cxx_compiler_version:          # [unix]
  - 14                         # [linux]
  - 19                         # [osx]

lbr_fri_client_sdk:
  - '1.11'
  - '1.14'
  - '1.15'
  - '1.16'
  - '1.17'
