[workspace]
name = "ros-jazzy"
description = "RoboStack repo to package ros-jazzy packages as conda packages"
authors = ["Tobias Fischer <tobias.fischer@qut.edu.au>", "Wolf Vollprecht <w.vollprecht@gmail.com>", "Silvio Traversaro <silvio@traversaro.it>"]
channels = ["https://prefix.dev/conda-forge"]
platforms = [
    # 2.17 is the glibc version used in centos 7
    { platform = "linux-64", glibc = "2.17" },
    { platform = "linux-aarch64", glibc = "2.17" },
    "osx-arm64",
    "osx-64",
    "win-64",
]
preview = ["pixi-build"]

[target.win.activation.env]
PYTHONIOENCODING = "utf-8"

[dependencies]
python = ">=3.12,<3.13"
rattler-build = ">=0.75.0,<0.76"
cmake = "<4"
# Some git repos may need git-lfs, see https://github.com/RoboStack/ros-jazzy/issues/118
git-lfs = ">=3.8.0,<4"
rattler-index = ">=0.30.11,<0.31"
vinca = { git = "https://github.com/RoboStack/vinca.git" }
# For local development uncomment:
# vinca.path = "../vinca"

[target.win-64.dependencies]
# patch is required by rattler-build
m2-patch = ">=2.7.6.3,<3"
# git is required by rattler-build
git = ">=2.55.0,<3"


[tasks]
generate-recipes = { cmd = "vinca -m", depends-on = ["remove-recipes"] }
generate-gha-workflows = { cmd = "vinca-gha --trigger-branch dummy_build_branch_as_it_is_unused -d ./recipes", depends-on = ["generate-recipes"] }
check-patches = { cmd = "python check_patches_clean_apply.py", depends-on = ["generate-recipes"] }
create_snapshot = { cmd = "vinca-snapshot -d jazzy -o rosdistro_snapshot.yaml" }
upload = "rattler-build upload anaconda -o robostack-jazzy -a $ANACONDA_API_TOKEN"
build_continue_on_failure = { cmd = "rattler-build build --recipe-dir ./recipes -m ./conda_build_config.yaml -c https://prefix.dev/robostack-jazzy -c https://prefix.dev/conda-forge --continue-on-failure --skip-existing", depends-on = ["generate-recipes"] }
sort = { cmd = "vinca-sort-vinca-lists {{ check }} vinca.yaml && vinca-sort-yaml-keys {{ check }} pkg_additional_info.yaml robostack.yaml rosdistro_additional_recipes.yaml", args = [{ arg = "check", default = "" }] }

[tasks.build]
cmd = "rattler-build build --recipe-dir ./recipes -m ./conda_build_config.yaml -c https://prefix.dev/robostack-jazzy -c https://prefix.dev/conda-forge --skip-existing"
depends-on = ["generate-recipes"]
description = "Build all packages, from the ./recipes dir. This will skip already existing packages, so it can be used to build only a subset of packages by first removing the recipes of the packages you want to rebuild (see `pixi run remove-recipes`)."

[tasks.remove-recipes]
cmd = "rm -rf recipes_only_patch; rm -rf recipes; mkdir recipes"
description = "Remove all generated recipes, before regenerating them."

[tasks.build-one]
cmd = "cp ./patch/{{ PACKAGE }}.*patch ./recipes/{{ PACKAGE }}/patch/; rattler-build build --recipe ./recipes/{{ PACKAGE }}/recipe.yaml -m ./conda_build_config.yaml -c https://prefix.dev/robostack-jazzy -c https://prefix.dev/conda-forge"
args = [{ arg = "PACKAGE", default = "ros-jazzy-ros-workspace" }]
description = "Build a single package, from the ./recipes dir. Add the `ros-jazzy-` prefix to the package name, e.g. `pixi build-one ros-jazzy-ros-workspace`"

