# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros2-moveit-setup-assistant
  version: 2.12.4
source:
  git: https://github.com/ros2-gbp/moveit2-release.git
  tag: release/jazzy/moveit_setup_assistant/2.12.4-1
  target_directory: ros2-moveit-setup-assistant/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 25
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://moveit.ros.org
  repository: https://github.com/ros-planning/moveit2
  license: BSD-3-Clause
  summary: Generates a configuration package that makes it easy to use MoveIt
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: osx
      then:
        - clang-tools ${{ (cxx_compiler_version ~ '.*') if cxx_compiler_version is defined else '*' }}
    - if: build_platform != target_platform
      then:
        - qt-main
  host:
    - ${{ 'libgl-devel' if linux }}
    - ${{ 'libopengl-devel' if linux }}
    - if: build_platform == target_platform
      then:
        - pkg-config
    - libgl-devel
    - libopengl-devel
    - numpy
    - pip
    - python
    - qt-main
    - ros2-ament-cmake
    - ros2-ament-cmake-gtest
    - ros2-ament-index-cpp
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-moveit-resources-panda-moveit-config
    - ros2-moveit-setup-framework
    - ros2-moveit-setup-srdf-plugins
    - ros2-pluginlib
    - ros2-rclcpp
    - ros2-ros-environment
    - ros2-ros-workspace
  run:
    - libgl-devel
    - libopengl-devel
    - python
    - qt-main
    - ros2-ament-index-cpp
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-moveit-configs-utils
    - ros2-moveit-setup-app-plugins
    - ros2-moveit-setup-controllers
    - ros2-moveit-setup-core-plugins
    - ros2-moveit-setup-framework
    - ros2-moveit-setup-srdf-plugins
    - ros2-pluginlib
    - ros2-rclcpp
    - ros2-ros-workspace
