# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-moveit-kinematics
  version: 2.12.4
source:
  git: https://github.com/ros2-gbp/moveit2-release.git
  tag: release/jazzy/moveit_kinematics/2.12.4-1
  target_directory: ros-jazzy-moveit-kinematics/src/work
  patches:
    - patch/ros-jazzy-moveit-kinematics.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://moveit.ros.org
  repository: https://github.com/moveit/moveit2
  license: BSD-3-Clause
  summary: Package for all inverse kinematics solvers in MoveIt
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - eigen
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-class-loader
    - ros-jazzy-generate-parameter-library
    - ros-jazzy-launch-param-builder
    - ros-jazzy-moveit-common
    - ros-jazzy-moveit-configs-utils
    - ros-jazzy-moveit-core
    - ros-jazzy-moveit-msgs
    - ros-jazzy-moveit-resources-fanuc-description
    - ros-jazzy-moveit-resources-fanuc-moveit-config
    - ros-jazzy-moveit-resources-panda-description
    - ros-jazzy-moveit-resources-panda-moveit-config
    - ros-jazzy-moveit-ros-planning
    - ros-jazzy-orocos-kdl-vendor
    - ros-jazzy-pluginlib
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-testing
    - ros-jazzy-ros-workspace
    - ros-jazzy-rsl
    - ros-jazzy-tf2
    - ros-jazzy-tf2-kdl
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - eigen
    - lxml
    - python
    - ros-jazzy-class-loader
    - ros-jazzy-generate-parameter-library
    - ros-jazzy-moveit-common
    - ros-jazzy-moveit-core
    - ros-jazzy-moveit-msgs
    - ros-jazzy-moveit-ros-planning
    - ros-jazzy-orocos-kdl-vendor
    - ros-jazzy-pluginlib
    - ros-jazzy-ros-workspace
    - ros-jazzy-rsl
    - ros-jazzy-tf2
    - ros-jazzy-tf2-kdl
    - ros-jazzy-urdfdom
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
