# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-clearpath-manipulators
  version: 2.8.5
source:
  git: https://github.com/clearpath-gbp/clearpath_common-release.git
  tag: release/jazzy/clearpath_manipulators/2.8.5-1
  target_directory: ros-jazzy-clearpath-manipulators/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: BSD-3-Clause
  summary: MoveIt configuration built around Clearpath Configuration
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - python
    - ros-jazzy-clearpath-manipulators-description
    - ros-jazzy-gripper-controllers
    - ros-jazzy-moveit-configs-utils
    - ros-jazzy-moveit-kinematics
    - ros-jazzy-moveit-planners
    - ros-jazzy-moveit-planners-chomp
    - ros-jazzy-moveit-ros-move-group
    - ros-jazzy-moveit-ros-warehouse
    - ros-jazzy-moveit-setup-srdf-plugins
    - ros-jazzy-moveit-simple-controller-manager
    - ros-jazzy-position-controllers
    - ros-jazzy-ros-workspace
    - ros-jazzy-tf2-ros
    - ros-jazzy-xacro
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
