# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-state-interfaces-broadcaster
  version: 4.37.0
source:
  git: https://github.com/ros2-gbp/ros2_controllers-release.git
  tag: release/jazzy/state_interfaces_broadcaster/4.37.0-1
  target_directory: ros-jazzy-state-interfaces-broadcaster/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://control.ros.org
  repository: https://github.com/ros-controls/ros2_controllers/
  license: Apache-2.0
  summary: Broadcaster to publish the requested hardware interface states
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gmock
    - ros-jazzy-backward-ros
    - ros-jazzy-control-msgs
    - ros-jazzy-controller-interface
    - ros-jazzy-controller-manager
    - ros-jazzy-generate-parameter-library
    - ros-jazzy-hardware-interface
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-lifecycle
    - ros-jazzy-realtime-tools
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-ros2-control-cmake
    - ros-jazzy-ros2-control-test-assets
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - python
    - ros-jazzy-backward-ros
    - ros-jazzy-control-msgs
    - ros-jazzy-controller-interface
    - ros-jazzy-generate-parameter-library
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-lifecycle
    - ros-jazzy-realtime-tools
    - ros-jazzy-ros-workspace
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
