# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros2-fastrtps
  version: 2.14.7
source:
  git: https://github.com/ros2-gbp/fastdds-release.git
  tag: release/jazzy/fastrtps/2.14.7-1
  target_directory: ros2-fastrtps/src/work
  patches:
    - patch/ros-jazzy-fastrtps.patch

build:
  script: ${{ '$RECIPE_DIR/build_catkin.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_catkin.bat' }}
  number: 25
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.eprosima.com/
  repository: https://github.com/eProsima/Fast-DDS
  license: Apache-2.0
  summary: '*eprosima Fast DDS* (formerly Fast RTPS) is a C++ implementation of the DDS (Data Distribution Service) standard of the OMG (Object Management Group). eProsima Fast DDS implements the RTPS (Real Time Publish Subscribe) protocol, which provides publisher-subscriber communications over unreliable transports such as UDP, as defined and maintained by the Object Management Group (OMG) consortium. RTPS is also the wire interoperability protocol defined for the Data Distribution Service (DDS) standard. *eProsima Fast DDS* expose an API to access directly the RTPS protocol, giving the user full access to the protocol internals.'
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: osx
      then:
        - clang-tools ${{ (cxx_compiler_version ~ '.*') if cxx_compiler_version is defined else '*' }}
  host:
    - asio
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - openssl
    - pip
    - python
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-fastcdr
    - ros2-foonathan-memory-vendor
    - ros2-ros-environment
    - ros2-ros-workspace
    - tinyxml2
  run:
    - openssl
    - python
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-fastcdr
    - ros2-foonathan-memory-vendor
    - ros2-ros-workspace
    - tinyxml2
