# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-behaviortree-cpp
  version: 4.8.3
source:
  git: https://github.com/ros2-gbp/behaviortree_cpp_v4-release.git
  tag: release/jazzy/behaviortree_cpp/4.8.3-1
  target_directory: ros-jazzy-behaviortree-cpp/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: MIT
  summary: This package provides the Behavior Trees core library.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - cppzmq
    - libboost-devel
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-index-cpp
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-tinyxml2-vendor
    - ros2-distro-mutex 0.14.* jazzy_*
    - sqlite
    - sqlite 3.*
    - tinyxml2
    - zeromq
  run:
    - cppzmq
    - libboost
    - python
    - ros-jazzy-ament-index-cpp
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-workspace
    - ros-jazzy-tinyxml2-vendor
    - ros2-distro-mutex 0.14.* jazzy_*
    - sqlite
    - tinyxml2
    - zeromq
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
