# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-launch-ros
  version: 0.26.11
source:
  git: https://github.com/ros2-gbp/launch_ros-release.git
  tag: release/jazzy/launch_ros/0.26.11-1
  target_directory: ros-jazzy-launch-ros/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_python.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_python.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: Apache-2.0
  summary: ROS specific extensions to the launch tool.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - importlib-metadata
    - numpy
    - pip
    - pytest
    - python
    - pyyaml
    - ros-jazzy-ament-copyright
    - ros-jazzy-ament-flake8
    - ros-jazzy-ament-index-python
    - ros-jazzy-ament-pep257
    - ros-jazzy-composition-interfaces
    - ros-jazzy-launch
    - ros-jazzy-lifecycle-msgs
    - ros-jazzy-osrf-pycommon
    - ros-jazzy-rclpy
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros2-distro-mutex 0.14.* jazzy_*
    - setuptools
  run:
    - importlib-metadata
    - python
    - pyyaml
    - ros-jazzy-ament-index-python
    - ros-jazzy-composition-interfaces
    - ros-jazzy-launch
    - ros-jazzy-lifecycle-msgs
    - ros-jazzy-osrf-pycommon
    - ros-jazzy-rclpy
    - ros-jazzy-ros-workspace
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
