# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-controller-manager
  version: 4.43.0
source:
  git: https://github.com/ros2-gbp/ros2_control-release.git
  tag: release/jazzy/controller_manager/4.43.0-1
  target_directory: ros-jazzy-controller-manager/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: Apache-2.0
  summary: The main runnable entrypoint of ros2_control and home of controller management and resource management.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - coverage
    - fmt
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gen-version-h
    - ros-jazzy-ament-cmake-gmock
    - ros-jazzy-ament-cmake-pytest
    - ros-jazzy-ament-cmake-python
    - ros-jazzy-backward-ros
    - ros-jazzy-controller-interface
    - ros-jazzy-controller-manager-msgs
    - ros-jazzy-diagnostic-updater
    - ros-jazzy-example-interfaces
    - ros-jazzy-generate-parameter-library
    - ros-jazzy-hardware-interface
    - ros-jazzy-hardware-interface-testing
    - ros-jazzy-launch-testing
    - ros-jazzy-libstatistics-collector
    - ros-jazzy-lifecycle-msgs
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-realtime-tools
    - ros-jazzy-robot-state-publisher
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-ros2-control-cmake
    - ros-jazzy-ros2-control-test-assets
    - ros-jazzy-ros2pkg
    - ros-jazzy-std-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - fmt
    - python
    - pyyaml
    - ros-jazzy-backward-ros
    - ros-jazzy-controller-interface
    - ros-jazzy-controller-manager-msgs
    - ros-jazzy-diagnostic-updater
    - ros-jazzy-generate-parameter-library
    - ros-jazzy-hardware-interface
    - ros-jazzy-launch
    - ros-jazzy-launch-ros
    - ros-jazzy-launch-testing-ros
    - ros-jazzy-libstatistics-collector
    - ros-jazzy-lifecycle-msgs
    - ros-jazzy-pluginlib
    - ros-jazzy-rcl-interfaces
    - ros-jazzy-rclcpp
    - ros-jazzy-rclpy
    - ros-jazzy-realtime-tools
    - ros-jazzy-ros-workspace
    - ros-jazzy-ros2param
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
