# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-rclcpp-lifecycle
  version: 28.1.16
source:
  git: https://github.com/ros2-gbp/rclcpp-release.git
  tag: release/jazzy/rclcpp_lifecycle/28.1.16-1
  target_directory: ros-jazzy-rclcpp-lifecycle/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: Apache-2.0
  summary: Package containing a prototype for lifecycle implementation
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: target_platform != 'emscripten-wasm32'
      then:
        - ros-jazzy-mimick-vendor
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-cmake-ros
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-lifecycle-msgs
    - ros-jazzy-performance-test-fixture
    - ros-jazzy-rcl
    - ros-jazzy-rcl-interfaces
    - ros-jazzy-rcl-lifecycle
    - ros-jazzy-rclcpp
    - ros-jazzy-rcpputils
    - ros-jazzy-rcutils
    - ros-jazzy-rmw
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-typesupport-cpp
    - ros-jazzy-test-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - python
    - ros-jazzy-lifecycle-msgs
    - ros-jazzy-rcl
    - ros-jazzy-rcl-interfaces
    - ros-jazzy-rcl-lifecycle
    - ros-jazzy-rclcpp
    - ros-jazzy-rcutils
    - ros-jazzy-rmw
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-typesupport-cpp
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
