# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros2-resource-retriever
  version: 3.4.4
source:
  git: https://github.com/ros2-gbp/resource_retriever-release.git
  tag: release/jazzy/resource_retriever/3.4.4-1
  target_directory: ros2-resource-retriever/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 25
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://ros.org/wiki/resource_retriever
  repository: https://github.com/ros/resource_retriever
  license: BSD-3-Clause
  summary: This package retrieves data from url-format files such as http://, ftp://, package:// file://, etc., and loads the data into memory. The package:// url for ros packages is translated into a local file:// url. The resourse retriever was initially designed to load mesh files into memory, but it can be used for any type of data. The resource retriever is based on the the libcurl library.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: osx
      then:
        - clang-tools ${{ (cxx_compiler_version ~ '.*') if cxx_compiler_version is defined else '*' }}
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - pytest
    - python
    - ros2-ament-cmake-gtest
    - ros2-ament-cmake-pytest
    - ros2-ament-cmake-ros
    - ros2-ament-index-cpp
    - ros2-ament-index-python
    - ros2-ament-lint-auto
    - ros2-ament-lint-common
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-libcurl-vendor
    - ros2-python-cmake-module
    - ros2-ros-environment
    - ros2-ros-workspace
  run:
    - python
    - ros2-ament-index-cpp
    - ros2-ament-index-python
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-libcurl-vendor
    - ros2-ros-workspace
