# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-pal-statistics
  version: 2.7.0
source:
  git: https://github.com/ros2-gbp/pal_statistics-release.git
  tag: release/jazzy/pal_statistics/2.7.0-1
  target_directory: ros-jazzy-pal-statistics/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://github.com/pal-robotics/pal_statistics
  license: MIT
  summary: The pal_statistics package
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - libboost-devel
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake-auto
    - ros-jazzy-ament-cmake-gmock
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-cmake-pytest
    - ros-jazzy-ament-cmake-python
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-pal-statistics-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-lifecycle
    - ros-jazzy-rclpy
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - libboost-devel
    - python
    - ros-jazzy-pal-statistics-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-lifecycle
    - ros-jazzy-rclpy
    - ros-jazzy-ros-workspace
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
