# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-octomap-rviz-plugins
  version: 2.1.0
source:
  git: https://github.com/ros2-gbp/octomap_rviz_plugins-release.git
  tag: release/jazzy/octomap_rviz_plugins/2.1.0-1
  target_directory: ros-jazzy-octomap-rviz-plugins/src/work
  patches:
    - patch/ros-jazzy-octomap-rviz-plugins.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://ros.org/wiki/octomap_rviz_plugins
  license: BSD-3-Clause
  summary: A set of plugins for displaying occupancy information decoded from binary octomap messages.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: build_platform != target_platform
      then:
        - qt-main
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - octomap
    - pip
    - python
    - qt-main
    - ros-jazzy-ament-cmake-auto
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-octomap-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-rviz-common
    - ros-jazzy-rviz-default-plugins
    - ros-jazzy-rviz-rendering
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - python
    - qt-main
    - ros-jazzy-octomap-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-workspace
    - ros-jazzy-rviz-common
    - ros-jazzy-rviz-default-plugins
    - ros-jazzy-rviz-rendering
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
