# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-moveit-py
  version: 2.12.4
source:
  git: https://github.com/ros2-gbp/moveit2-release.git
  tag: release/jazzy/moveit_py/2.12.4-1
  target_directory: ros-jazzy-moveit-py/src/work
  patches:
    - patch/ros-jazzy-moveit-py.osx.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: BSD-3-Clause
  summary: Python binding for MoveIt 2
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: build_platform != target_platform
      then:
        - pybind11
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - pytest
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-pytest
    - ros-jazzy-geometry-msgs
    - ros-jazzy-moveit-core
    - ros-jazzy-moveit-ros-planning
    - ros-jazzy-moveit-ros-planning-interface
    - ros-jazzy-octomap-msgs
    - ros-jazzy-pybind11-vendor
    - ros-jazzy-rclcpp
    - ros-jazzy-rclpy
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros2-distro-mutex 0.14.* jazzy_*
    - pybind11
  run:
    - python
    - ros-jazzy-ament-index-python
    - ros-jazzy-geometry-msgs
    - ros-jazzy-moveit-core
    - ros-jazzy-moveit-ros-planning
    - ros-jazzy-moveit-ros-planning-interface
    - ros-jazzy-octomap-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-rclpy
    - ros-jazzy-ros-workspace
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
