# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-geometric-shapes
  version: 2.3.2
source:
  git: https://github.com/ros2-gbp/geometric_shapes-release.git
  tag: release/jazzy/geometric_shapes/2.3.2-1
  target_directory: ros-jazzy-geometric-shapes/src/work
  patches:
    - patch/ros-jazzy-geometric-shapes.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://ros.org/wiki/geometric_shapes
  license: BSD-3-Clause
  summary: This package contains generic definitions of geometric shapes and bodies.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: target_platform == 'emscripten-wasm32'
      then:
        - ros-jazzy-rosidl-default-generators
  host:
    - assimp
    - if: build_platform == target_platform
      then:
        - pkg-config
    - eigen
    - fcl
    - libboost-devel
    - numpy
    - octomap
    - pip
    - pkg-config
    - python
    - qhull
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-copyright
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-cmake
    - ros-jazzy-console-bridge-vendor
    - ros-jazzy-eigen-stl-containers
    - ros-jazzy-eigen3-cmake-module
    - ros-jazzy-geometry-msgs
    - ros-jazzy-random-numbers
    - ros-jazzy-rclcpp
    - ros-jazzy-resource-retriever
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-default-generators
    - ros-jazzy-shape-msgs
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - assimp
    - eigen
    - libboost
    - libboost-devel
    - python
    - qhull
    - ros-jazzy-console-bridge-vendor
    - ros-jazzy-eigen-stl-containers
    - ros-jazzy-eigen3-cmake-module
    - ros-jazzy-geometry-msgs
    - ros-jazzy-random-numbers
    - ros-jazzy-rclcpp
    - ros-jazzy-resource-retriever
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-default-runtime
    - ros-jazzy-shape-msgs
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
