# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-moveit-task-constructor-capabilities
  version: 0.1.3
source:
  git: https://github.com/wep21/moveit_task_constructor-release.git
  tag: release/jazzy/moveit_task_constructor_capabilities/0.1.3-1
  target_directory: ros-jazzy-moveit-task-constructor-capabilities/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: BSD-3-Clause
  summary: MoveGroupCapabilites to interact with MoveIt
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - fmt
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-launch-testing
    - ros-jazzy-launch-testing-ament-cmake
    - ros-jazzy-moveit-configs-utils
    - ros-jazzy-moveit-core
    - ros-jazzy-moveit-resources-panda-moveit-config
    - ros-jazzy-moveit-ros-move-group
    - ros-jazzy-moveit-ros-planning
    - ros-jazzy-moveit-task-constructor-core
    - ros-jazzy-moveit-task-constructor-msgs
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp-action
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-std-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - fmt
    - python
    - ros-jazzy-moveit-core
    - ros-jazzy-moveit-ros-move-group
    - ros-jazzy-moveit-ros-planning
    - ros-jazzy-moveit-task-constructor-core
    - ros-jazzy-moveit-task-constructor-msgs
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp-action
    - ros-jazzy-ros-workspace
    - ros-jazzy-std-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
