# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros2-random-numbers
  version: 2.0.5
source:
  git: https://github.com/ros2-gbp/random_numbers-release.git
  tag: release/jazzy/random_numbers/2.0.5-1
  target_directory: ros2-random-numbers/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 25
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://ros.org/wiki/random_numbers
  repository: https://github.com/ros-planning/random_numbers
  license: BSD-3-Clause
  summary: This library contains wrappers for generating floating point values, integers, quaternions using boost libraries. The constructor of the wrapper is guaranteed to be thread safe and initialize its random number generator to a random seed. Seeds are obtained using a separate and different random number generator.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: osx
      then:
        - clang-tools ${{ (cxx_compiler_version ~ '.*') if cxx_compiler_version is defined else '*' }}
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - libboost-devel
    - numpy
    - pip
    - python
    - ros2-ament-cmake
    - ros2-ament-cmake-copyright
    - ros2-ament-lint-auto
    - ros2-ament-lint-cmake
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-ros-environment
    - ros2-ros-workspace
  run:
    - libboost
    - libboost-devel
    - python
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-ros-workspace
