# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros2-roboplan-examples
  version: 0.6.1
source:
  git: https://github.com/ros2-gbp/roboplan-release.git
  tag: release/jazzy/roboplan_examples/0.6.1-1
  target_directory: ros2-roboplan-examples/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 21
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://roboplan.readthedocs.io
  repository: https://github.com/open-planning/roboplan
  license: MIT
  summary: Basic examples of RoboPlan.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: osx
      then:
        - clang-tools ${{ (cxx_compiler_version ~ '.*') if cxx_compiler_version is defined else '*' }}
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros2-ament-cmake
    - ros2-ament-cmake-pytest
    - ros2-distro-mutex 0.16.* jazzy_*
    - ros2-roboplan
    - ros2-roboplan-cartesian-planning
    - ros2-roboplan-example-models
    - ros2-roboplan-oink
    - ros2-roboplan-rrt
    - ros2-roboplan-simple-ik
    - ros2-roboplan-toppra
    - ros2-ros-environment
    - ros2-ros-workspace
  run:
    - python
    - ros2-distro-mutex 0.16.* jazzy_*
    - ros2-roboplan
    - ros2-roboplan-cartesian-planning
    - ros2-roboplan-example-models
    - ros2-roboplan-oink
    - ros2-roboplan-rrt
    - ros2-roboplan-simple-ik
    - ros2-roboplan-toppra
    - ros2-ros-workspace
    - ros2-xacro
