# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-desktop
  version: 0.11.0
source:
  git: https://github.com/ros2-gbp/variants-release.git
  tag: release/jazzy/desktop/0.11.0-1
  target_directory: ros-jazzy-desktop/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: Apache-2.0
  summary: A package which extends 'ros_base' and includes high level packages like vizualization tools and demos.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - python
    - ros-jazzy-action-tutorials-cpp
    - ros-jazzy-action-tutorials-interfaces
    - ros-jazzy-action-tutorials-py
    - ros-jazzy-angles
    - ros-jazzy-composition
    - ros-jazzy-demo-nodes-cpp
    - ros-jazzy-demo-nodes-cpp-native
    - ros-jazzy-demo-nodes-py
    - ros-jazzy-depthimage-to-laserscan
    - ros-jazzy-dummy-map-server
    - ros-jazzy-dummy-robot-bringup
    - ros-jazzy-dummy-sensors
    - ros-jazzy-examples-rclcpp-minimal-action-client
    - ros-jazzy-examples-rclcpp-minimal-action-server
    - ros-jazzy-examples-rclcpp-minimal-client
    - ros-jazzy-examples-rclcpp-minimal-composition
    - ros-jazzy-examples-rclcpp-minimal-publisher
    - ros-jazzy-examples-rclcpp-minimal-service
    - ros-jazzy-examples-rclcpp-minimal-subscriber
    - ros-jazzy-examples-rclcpp-minimal-timer
    - ros-jazzy-examples-rclcpp-multithreaded-executor
    - ros-jazzy-examples-rclpy-executors
    - ros-jazzy-examples-rclpy-minimal-action-client
    - ros-jazzy-examples-rclpy-minimal-action-server
    - ros-jazzy-examples-rclpy-minimal-client
    - ros-jazzy-examples-rclpy-minimal-publisher
    - ros-jazzy-examples-rclpy-minimal-service
    - ros-jazzy-examples-rclpy-minimal-subscriber
    - ros-jazzy-image-tools
    - ros-jazzy-intra-process-demo
    - ros-jazzy-joy
    - ros-jazzy-lifecycle
    - ros-jazzy-logging-demo
    - ros-jazzy-pcl-conversions
    - ros-jazzy-pendulum-msgs
    - ros-jazzy-quality-of-service-demo-cpp
    - ros-jazzy-quality-of-service-demo-py
    - ros-jazzy-ros-base
    - ros-jazzy-ros-workspace
    - ros-jazzy-rqt-common-plugins
    - ros-jazzy-rviz-default-plugins
    - ros-jazzy-rviz2
    - ros-jazzy-teleop-twist-joy
    - ros-jazzy-teleop-twist-keyboard
    - ros-jazzy-topic-monitor
    - ros-jazzy-turtlesim
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
tests:
  - script:
      - ros2 pkg prefix desktop
    requirements:
      run:
        - ros-jazzy-ros2pkg
