# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros2-apriltag-mit
  version: 1.0.3
source:
  git: https://github.com/ros2-gbp/apriltag_mit-release.git
  tag: release/jazzy/apriltag_mit/1.0.3-1
  target_directory: ros2-apriltag-mit/src/work
  patches:
    - patch/ros-jazzy-apriltag-mit.patch
    - patch/ros-jazzy-apriltag-mit.win.patch

build:
  script: ${{ '$RECIPE_DIR/build_catkin.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_catkin.bat' }}
  number: 25
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  repository: https://github.com/ros-misc-utilities/apriltag_mit
  license: LGPL-2.1-or-later
  summary: ROS2 package wrapper for the MIT apriltag detector
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: osx
      then:
        - clang-tools ${{ (cxx_compiler_version ~ '.*') if cxx_compiler_version is defined else '*' }}
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - clang-tools
    - eigen
    - eigen-abi-devel
    - libboost-devel
    - libopencv
    - numpy
    - pip
    - py-opencv
    - python
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-ros-environment
    - ros2-ros-workspace
  run:
    - clang-tools
    - eigen
    - eigen-abi-devel
    - libboost-devel
    - libopencv
    - py-opencv
    - python
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-ros-workspace
