# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-sbg-driver
  version: 3.3.2
source:
  git: https://github.com/SBG-Systems/sbg_ros2-release.git
  tag: release/jazzy/sbg_driver/3.3.2-1
  target_directory: ros-jazzy-sbg-driver/src/work
  patches:
    - patch/ros-jazzy-sbg-driver.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://wiki.ros.org/sbg_driver
  license: MIT
  summary: ROS driver package for communication with the SBG navigation systems.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: target_platform == 'emscripten-wasm32'
      then:
        - ros-jazzy-rosidl-default-generators
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-geometry-msgs
    - ros-jazzy-nav-msgs
    - ros-jazzy-nmea-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-default-generators
    - ros-jazzy-rtcm-msgs
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros-jazzy-std-srvs
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-msgs
    - ros-jazzy-tf2-ros
    - ros-jazzy-urdf
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - python
    - ros-jazzy-geometry-msgs
    - ros-jazzy-nav-msgs
    - ros-jazzy-nmea-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-default-runtime
    - ros-jazzy-rtcm-msgs
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros-jazzy-std-srvs
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-msgs
    - ros-jazzy-tf2-ros
    - ros-jazzy-urdf
    - ros-jazzy-xacro
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
