# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-cartographer-ros
  version: 2.0.9003
source:
  git: https://github.com/ros2-gbp/cartographer_ros-release.git
  tag: release/jazzy/cartographer_ros/2.0.9003-2
  target_directory: ros-jazzy-cartographer-ros/src/work
  patches:
    - patch/ros-jazzy-cartographer-ros.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://github.com/cartographer-project/cartographer_ros
  license: Apache-2.0
  summary: Cartographer is a system that provides real-time simultaneous localization and mapping (SLAM) in 2D and 3D across multiple platforms and sensor configurations. This package provides Cartographer's ROS integration.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - cartographer 2.*
    - eigen
    - gflags
    - glog
    - gmock
    - libabseil
    - libboost-devel
    - numpy
    - pcl
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-cartographer
    - ros-jazzy-cartographer-ros-msgs
    - ros-jazzy-geometry-msgs
    - ros-jazzy-nav-msgs
    - ros-jazzy-pcl-conversions
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosbag2-cpp
    - ros-jazzy-rosbag2-storage
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-eigen
    - ros-jazzy-tf2-msgs
    - ros-jazzy-tf2-ros
    - ros-jazzy-urdf
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - sphinx
    - vtk-base
  run:
    - eigen
    - gflags
    - glog
    - libabseil
    - libboost-devel
    - pcl
    - python
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-cartographer
    - ros-jazzy-cartographer-ros-msgs
    - ros-jazzy-geometry-msgs
    - ros-jazzy-launch
    - ros-jazzy-nav-msgs
    - ros-jazzy-pcl-conversions
    - ros-jazzy-rclcpp
    - ros-jazzy-robot-state-publisher
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosbag2-cpp
    - ros-jazzy-rosbag2-storage
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-eigen
    - ros-jazzy-tf2-msgs
    - ros-jazzy-tf2-ros
    - ros-jazzy-urdf
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - vtk-base
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
