# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-control-toolbox
  version: 4.9.0
source:
  git: https://github.com/ros2-gbp/control_toolbox-release.git
  tag: release/jazzy/control_toolbox/4.9.0-1
  target_directory: ros-jazzy-control-toolbox/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://control.ros.org
  repository: https://github.com/ros-controls/control_toolbox/
  license: Apache-2.0
  summary: The control toolbox contains modules that are useful across all controllers.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - eigen
    - fmt
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gmock
    - ros-jazzy-backward-ros
    - ros-jazzy-control-msgs
    - ros-jazzy-filters
    - ros-jazzy-generate-parameter-library
    - ros-jazzy-geometry-msgs
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-lifecycle
    - ros-jazzy-rcutils
    - ros-jazzy-realtime-tools
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-ros2-control-cmake
    - ros-jazzy-tf2
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-ros
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - eigen
    - fmt
    - python
    - ros-jazzy-backward-ros
    - ros-jazzy-control-msgs
    - ros-jazzy-filters
    - ros-jazzy-generate-parameter-library
    - ros-jazzy-geometry-msgs
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-rcutils
    - ros-jazzy-realtime-tools
    - ros-jazzy-ros-workspace
    - ros-jazzy-tf2
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-ros
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
tests:
  - script:
      - cmake-package-check control_toolbox --targets control_toolbox::control_toolbox control_toolbox::rate_limiter control_toolbox::low_pass_filter
    requirements:
      run:
        - cmake-package-check
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
