# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-cloudini-lib
  version: 0.11.1
source:
  git: https://github.com/facontidavide/cloudini.git
  tag: 0.11.1
  target_directory: ros-jazzy-cloudini-lib/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: Apache-2.0
  summary: Main library of Cloudini, the pointcloud compression library
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - lz4
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-mcap-vendor
    - ros-jazzy-pcl-ros
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros2-distro-mutex 0.14.* jazzy_*
    - zstd
  run:
    - lz4
    - python
    - ros-jazzy-mcap-vendor
    - ros-jazzy-pcl-ros
    - ros-jazzy-ros-workspace
    - ros2-distro-mutex 0.14.* jazzy_*
    - zstd
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
