# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-rqt-bag-plugins
  version: 1.5.6
source:
  git: https://github.com/ros2-gbp/rqt_bag-release.git
  tag: release/jazzy/rqt_bag_plugins/1.5.6-1
  target_directory: ros-jazzy-rqt-bag-plugins/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_python.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_python.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://wiki.ros.org/rqt_bag
  repository: https://github.com/ros-visualization/rqt_bag
  license: BSD-3-Clause OR HPND
  summary: rqt_bag provides a GUI plugin for displaying and replaying ROS bag files.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - pytest
    - python
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros2-distro-mutex 0.14.* jazzy_*
    - setuptools
  run:
    - numpy
    - pillow
    - pycairo
    - python
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-geometry-msgs
    - ros-jazzy-rclpy
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosbag2
    - ros-jazzy-rqt-bag
    - ros-jazzy-rqt-gui
    - ros-jazzy-rqt-gui-py
    - ros-jazzy-rqt-plot
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
