# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-mavros
  version: 2.14.0
source:
  git: https://github.com/ros2-gbp/mavros-release.git
  tag: release/jazzy/mavros/2.14.0-1
  target_directory: ros-jazzy-mavros/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://wiki.ros.org/mavros
  repository: https://github.com/mavlink/mavros.git
  license: GPL-3.0-only OR LGPL-3.0-only OR BSD-3-Clause
  summary: MAVROS -- MAVLink extendable communication node for ROS with proxy for Ground Control Station.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - console_bridge
    - eigen
    - geographiclib-cpp
    - gmock
    - gtest
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gmock
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-cmake-pytest
    - ros-jazzy-ament-cmake-python
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-angles
    - ros-jazzy-diagnostic-msgs
    - ros-jazzy-diagnostic-updater
    - ros-jazzy-eigen-stl-containers
    - ros-jazzy-eigen3-cmake-module
    - ros-jazzy-geographic-msgs
    - ros-jazzy-geometry-msgs
    - ros-jazzy-libmavconn
    - ros-jazzy-mavlink
    - ros-jazzy-mavros-msgs
    - ros-jazzy-message-filters
    - ros-jazzy-nav-msgs
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-components
    - ros-jazzy-rcpputils
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros-jazzy-std-srvs
    - ros-jazzy-tf2-eigen
    - ros-jazzy-tf2-ros
    - ros-jazzy-trajectory-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - click
    - console_bridge
    - eigen
    - geographiclib-cpp
    - python
    - ros-jazzy-diagnostic-msgs
    - ros-jazzy-diagnostic-updater
    - ros-jazzy-eigen-stl-containers
    - ros-jazzy-eigen3-cmake-module
    - ros-jazzy-geographic-msgs
    - ros-jazzy-geometry-msgs
    - ros-jazzy-libmavconn
    - ros-jazzy-mavlink
    - ros-jazzy-mavros-msgs
    - ros-jazzy-message-filters
    - ros-jazzy-nav-msgs
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-components
    - ros-jazzy-rclpy
    - ros-jazzy-rcpputils
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-default-runtime
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros-jazzy-std-srvs
    - ros-jazzy-tf2-eigen
    - ros-jazzy-tf2-ros
    - ros-jazzy-trajectory-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
