# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-rviz-marker-tools
  version: 0.1.3
source:
  git: https://github.com/wep21/moveit_task_constructor-release.git
  tag: release/jazzy/rviz_marker_tools/0.1.3-1
  target_directory: ros-jazzy-rviz-marker-tools/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: BSD-3-Clause
  summary: Tools for marker creation / handling
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - eigen
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-eigen3-cmake-module
    - ros-jazzy-geometry-msgs
    - ros-jazzy-moveit-common
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2-eigen
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - urdfdom_headers
  run:
    - eigen
    - python
    - ros-jazzy-eigen3-cmake-module
    - ros-jazzy-geometry-msgs
    - ros-jazzy-moveit-common
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-workspace
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2-eigen
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
