# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-cv-bridge
  version: 4.1.0
source:
  git: https://github.com/ros2-gbp/vision_opencv-release.git
  tag: release/jazzy/cv_bridge/4.1.0-1
  target_directory: ros-jazzy-cv-bridge/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://www.ros.org/wiki/cv_bridge
  repository: https://github.com/ros-perception/vision_opencv/tree/ros2
  license: Apache-2.0 OR BSD-3-Clause
  summary: This contains CvBridge, which converts between ROS2 Image messages and OpenCV images.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - libboost-devel
    - libboost-python-devel
    - libopencv
    - numpy
    - pip
    - py-opencv
    - python
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-cmake-pytest
    - ros-jazzy-ament-cmake-ros
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-python-cmake-module
    - ros-jazzy-rclcpp
    - ros-jazzy-rcpputils
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-sensor-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - libboost-python
    - libopencv
    - numpy
    - py-opencv
    - python
    - ros-jazzy-ament-index-python
    - ros-jazzy-rclcpp
    - ros-jazzy-rcpputils
    - ros-jazzy-ros-workspace
    - ros-jazzy-sensor-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
