# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-robot-localization
  version: 3.8.3
source:
  git: https://github.com/ros2-gbp/robot_localization-release.git
  tag: release/jazzy/robot_localization/3.8.3-1
  target_directory: ros-jazzy-robot-localization/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://ros.org/wiki/robot_localization
  license: Apache-2.0
  summary: Provides nonlinear state estimation through sensor fusion of an abritrary number of sensors.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: target_platform == 'emscripten-wasm32'
      then:
        - ros-jazzy-rosidl-default-generators
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - eigen
    - geographiclib-cpp
    - libboost-devel
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-angles
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-diagnostic-msgs
    - ros-jazzy-diagnostic-updater
    - ros-jazzy-geographic-msgs
    - ros-jazzy-geometry-msgs
    - ros-jazzy-launch-ros
    - ros-jazzy-launch-testing-ament-cmake
    - ros-jazzy-message-filters
    - ros-jazzy-nav-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-rmw-implementation
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-default-generators
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros-jazzy-std-srvs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-eigen
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-ros
    - ros-jazzy-yaml-cpp-vendor
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - eigen
    - geographiclib-cpp
    - libboost-devel
    - python
    - ros-jazzy-angles
    - ros-jazzy-diagnostic-msgs
    - ros-jazzy-diagnostic-updater
    - ros-jazzy-geographic-msgs
    - ros-jazzy-geometry-msgs
    - ros-jazzy-message-filters
    - ros-jazzy-nav-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-rmw-implementation
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-default-runtime
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros-jazzy-std-srvs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-eigen
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-ros
    - ros-jazzy-yaml-cpp-vendor
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
