# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-rqt-graph
  version: 1.5.6
source:
  git: https://github.com/ros2-gbp/rqt_graph-release.git
  tag: release/jazzy/rqt_graph/1.5.6-1
  target_directory: ros-jazzy-rqt-graph/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_python.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_python.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://wiki.ros.org/rqt_graph
  repository: https://github.com/ros-visualization/rqt_graph
  license: BSD-3-Clause
  summary: rqt_graph provides a GUI plugin for visualizing the ROS computation graph.<br/>Its components are made generic so that other packages where you want to achieve graph representation can depend upon this pkg (use<a href="http://www.ros.org/wiki/rqt_dep">rqt_dep</a>to find out the pkgs that depend. rqt_dep itself depends on rqt_graph too).
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - pytest
    - python
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros2-distro-mutex 0.14.* jazzy_*
    - setuptools
  run:
    - python
    - ros-jazzy-ament-index-python
    - ros-jazzy-python-qt-binding
    - ros-jazzy-qt-dotgraph
    - ros-jazzy-ros-workspace
    - ros-jazzy-rqt-gui
    - ros-jazzy-rqt-gui-py
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
