# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-sick-scan-xd
  version: 3.8.0
source:
  git: https://github.com/ros2-gbp/sick_scan_xd-release.git
  tag: release/jazzy/sick_scan_xd/3.8.0-1
  target_directory: ros-jazzy-sick-scan-xd/src/work
  patches:
    - patch/ros-jazzy-sick-scan-xd.osx.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  repository: https://github.com/SICKAG/sick_scan_xd
  license: Apache-2.0
  summary: ROS 1 and 2 driver for SICK scanner
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: target_platform == 'emscripten-wasm32'
      then:
        - ros-jazzy-rosidl-default-generators
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-diagnostic-msgs
    - ros-jazzy-diagnostic-updater
    - ros-jazzy-geometry-msgs
    - ros-jazzy-nav-msgs
    - ros-jazzy-rcl-interfaces
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-default-generators
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-ros
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - python
    - ros-jazzy-diagnostic-msgs
    - ros-jazzy-diagnostic-updater
    - ros-jazzy-geometry-msgs
    - ros-jazzy-nav-msgs
    - ros-jazzy-rcl-interfaces
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-default-runtime
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-ros
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
