# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-udp-driver
  version: 1.2.0
source:
  git: https://github.com/ros2-gbp/transport_drivers-release.git
  tag: release/jazzy/udp_driver/1.2.0-4
  target_directory: ros-jazzy-udp-driver/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  repository: https://github.com/ros-drivers/transport_drivers
  license: Apache-2.0
  summary: A library to write Synchronous and Asynchronous networking applications, ROS and ROS2 nodes
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - asio
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake-auto
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-asio-cmake-module
    - ros-jazzy-io-context
    - ros-jazzy-lifecycle-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-components
    - ros-jazzy-rclcpp-lifecycle
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-std-msgs
    - ros-jazzy-udp-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - asio
    - python
    - ros-jazzy-io-context
    - ros-jazzy-lifecycle-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-components
    - ros-jazzy-rclcpp-lifecycle
    - ros-jazzy-ros-workspace
    - ros-jazzy-std-msgs
    - ros-jazzy-udp-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
