# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-grid-map-costmap-2d
  version: 2.2.2
source:
  git: https://github.com/ros2-gbp/grid_map-release.git
  tag: release/jazzy/grid_map_costmap_2d/2.2.2-2
  target_directory: ros-jazzy-grid-map-costmap-2d/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://github.com/anybotics/grid_map
  license: BSD-3-Clause
  summary: Interface for grid maps to the costmap_2d format.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-geometry-msgs
    - ros-jazzy-grid-map-cmake-helpers
    - ros-jazzy-grid-map-core
    - ros-jazzy-nav2-costmap-2d
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-ros
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - python
    - ros-jazzy-geometry-msgs
    - ros-jazzy-grid-map-core
    - ros-jazzy-nav2-costmap-2d
    - ros-jazzy-ros-workspace
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-ros
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
