package:
  name: ros-jazzy-urdfdom-headers
  version: "1.1.2"

build:
  number: 7

requirements:
  run:
    - urdfdom_headers ==1.1.2
    - python 3.12.* *_cpython

about:
  homepage: https://github.com/conda-forge/urdfdom_headers-feedstock
  license: BSD-3-Clause
  summary: |
    Headers for URDF parsers
extra:
  recipe-maintainers:
    - ros-forge
