# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-dual-laser-merger
  version: 0.3.1
source:
  git: https://github.com/ros2-gbp/dual_laser_merger-release.git
  tag: release/jazzy/dual_laser_merger/0.3.1-1
  target_directory: ros-jazzy-dual-laser-merger/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: Apache-2.0
  summary: merge dual lidar's scans.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - libboost-devel
    - numpy
    - pcl
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-auto
    - ros-jazzy-ament-copyright
    - ros-jazzy-ament-cpplint
    - ros-jazzy-ament-flake8
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-ament-pep257
    - ros-jazzy-ament-xmllint
    - ros-jazzy-geometry-msgs
    - ros-jazzy-laser-geometry
    - ros-jazzy-message-filters
    - ros-jazzy-pcl-conversions
    - ros-jazzy-pcl-ros
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-components
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-tf2
    - ros-jazzy-tf2-ros
    - ros-jazzy-tf2-sensor-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - vtk-base
  run:
    - libboost-devel
    - pcl
    - python
    - ros-jazzy-geometry-msgs
    - ros-jazzy-laser-geometry
    - ros-jazzy-message-filters
    - ros-jazzy-pcl-conversions
    - ros-jazzy-pcl-ros
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-components
    - ros-jazzy-ros-workspace
    - ros-jazzy-tf2
    - ros-jazzy-tf2-ros
    - ros-jazzy-tf2-sensor-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - vtk-base
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
