# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-rosbridge-server
  version: 2.4.2
source:
  git: https://github.com/ros2-gbp/rosbridge_suite-release.git
  tag: release/jazzy/rosbridge_server/2.4.2-1
  target_directory: ros-jazzy-rosbridge-server/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://ros.org/wiki/rosbridge_server
  repository: https://github.com/RobotWebTools/rosbridge_suite
  license: BSD-3-Clause
  summary: A WebSocket interface to rosbridge.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - autobahn
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-action-msgs
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-mypy
    - ros-jazzy-ament-cmake-python
    - ros-jazzy-example-interfaces
    - ros-jazzy-launch
    - ros-jazzy-launch-ros
    - ros-jazzy-launch-testing-ament-cmake
    - ros-jazzy-rcl-interfaces
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-std-srvs
    - ros2-distro-mutex 0.14.* jazzy_*
    - twisted
  run:
    - python
    - ros-jazzy-rclpy
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosapi
    - ros-jazzy-rosbridge-library
    - ros-jazzy-rosbridge-msgs
    - ros-jazzy-std-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - tornado
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
