# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-robot-state-publisher
  version: 3.3.3
source:
  git: https://github.com/ros2-gbp/robot_state_publisher-release.git
  tag: release/jazzy/robot_state_publisher/3.3.3-3
  target_directory: ros-jazzy-robot-state-publisher/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: BSD-3-Clause
  summary: This package take the joint angles of a robot as input, and publishes the 3D poses of the robot links to tf2, using a kinematic tree model of the robot.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-geometry-msgs
    - ros-jazzy-kdl-parser
    - ros-jazzy-launch-ros
    - ros-jazzy-launch-testing-ament-cmake
    - ros-jazzy-orocos-kdl-vendor
    - ros-jazzy-rcl-interfaces
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-components
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2-ros
    - ros-jazzy-urdf
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - python
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-geometry-msgs
    - ros-jazzy-kdl-parser
    - ros-jazzy-orocos-kdl-vendor
    - ros-jazzy-rcl-interfaces
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-components
    - ros-jazzy-ros-workspace
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2-ros
    - ros-jazzy-urdf
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
tests:
  - script:
      - if: osx and arm64
        then: export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp && launch_test robot_state_publisher_smoke_test_launch.py
        else: launch_test robot_state_publisher_smoke_test_launch.py
    requirements:
      run:
        - ros-jazzy-launch-testing-ros
    files:
      recipe:
        - robot_state_publisher_smoke_test_launch.py
