# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-ros-gz-sim
  version: 1.0.19
source:
  git: https://github.com/ros2-gbp/ros_ign-release.git
  tag: release/jazzy/ros_gz_sim/1.0.19-1
  target_directory: ros-jazzy-ros-gz-sim/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: Apache-2.0
  summary: Tools for using Gazebo Sim simulation with ROS.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - ${{ 'libgl-devel' if linux }}
    - ${{ 'libopengl-devel' if linux }}
    - if: build_platform == target_platform
      then:
        - pkg-config
    - gflags
    - numpy
    - pip
    - pkg-config
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-python
    - ros-jazzy-ament-index-python
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-geometry-msgs
    - ros-jazzy-gz-math-vendor
    - ros-jazzy-gz-msgs-vendor
    - ros-jazzy-gz-sim-vendor
    - ros-jazzy-gz-transport-vendor
    - ros-jazzy-launch
    - ros-jazzy-launch-ros
    - ros-jazzy-launch-testing
    - ros-jazzy-launch-testing-ament-cmake
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-action
    - ros-jazzy-rclcpp-components
    - ros-jazzy-rcpputils
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-gz-bridge
    - ros-jazzy-ros-gz-interfaces
    - ros-jazzy-ros-workspace
    - ros-jazzy-ros2pkg
    - ros-jazzy-simulation-interfaces
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-ros
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - gflags
    - python
    - ros-jazzy-ament-index-python
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-geometry-msgs
    - ros-jazzy-gz-math-vendor
    - ros-jazzy-gz-msgs-vendor
    - ros-jazzy-gz-sim-vendor
    - ros-jazzy-gz-transport-vendor
    - ros-jazzy-launch
    - ros-jazzy-launch-ros
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-action
    - ros-jazzy-rclcpp-components
    - ros-jazzy-rcpputils
    - ros-jazzy-ros-gz-interfaces
    - ros-jazzy-ros-workspace
    - ros-jazzy-ros2pkg
    - ros-jazzy-simulation-interfaces
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-ros
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
