# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-nav2-mppi-controller
  version: 1.3.11
source:
  git: https://github.com/SteveMacenski/navigation2-release.git
  tag: release/jazzy/nav2_mppi_controller/1.3.11-1
  target_directory: ros-jazzy-nav2-mppi-controller/src/work
  patches:
    - patch/ros-jazzy-nav2-mppi-controller.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: MIT
  summary: nav2_mppi_controller
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - ${{ 'clang <19' if osx }}
  host:
    - benchmark
    - if: build_platform == target_platform
      then:
        - pkg-config
    - llvm-openmp
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-cmake-ros
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-geometry-msgs
    - ros-jazzy-nav2-common
    - ros-jazzy-nav2-core
    - ros-jazzy-nav2-costmap-2d
    - ros-jazzy-nav2-msgs
    - ros-jazzy-nav2-util
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-eigen
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-ros
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - xsimd
    - xtensor ==0.24.7
  run:
    - benchmark
    - llvm-openmp
    - python
    - ros-jazzy-geometry-msgs
    - ros-jazzy-nav2-common
    - ros-jazzy-nav2-core
    - ros-jazzy-nav2-costmap-2d
    - ros-jazzy-nav2-msgs
    - ros-jazzy-nav2-util
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-workspace
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-eigen
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-ros
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - xsimd
    - xtensor
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
