# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-imu-filter-madgwick
  version: 2.1.5
source:
  git: https://github.com/ros2-gbp/imu_tools-release.git
  tag: release/jazzy/imu_filter_madgwick/2.1.5-1
  target_directory: ros-jazzy-imu-filter-madgwick/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://ros.org/wiki/imu_filter_madgwick
  license: GPL-1.0-or-later
  summary: Filter which fuses angular velocities, accelerations, and (optionally) magnetic readings from a generic IMU device into an orientation. Based on code by Sebastian Madgwick, http://www.x-io.co.uk/node/8#open_source_ahrs_and_imu_algorithms.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-geometry-msgs
    - ros-jazzy-nav-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-action
    - ros-jazzy-rclcpp-lifecycle
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-sensor-msgs
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-ros
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - python
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-geometry-msgs
    - ros-jazzy-nav-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-action
    - ros-jazzy-rclcpp-lifecycle
    - ros-jazzy-ros-workspace
    - ros-jazzy-sensor-msgs
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-ros
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
