# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-rviz-visual-tools
  version: 4.1.4
source:
  git: https://github.com/ros2-gbp/rviz_visual_tools-release.git
  tag: release/jazzy/rviz_visual_tools/4.1.4-4
  target_directory: ros-jazzy-rviz-visual-tools/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://github.com/PickNikRobotics/rviz_visual_tools
  repository: https://github.com/PickNikRobotics/rviz_visual_tools/
  license: BSD-3-Clause
  summary: Utility functions for displaying and debugging data in Rviz via published markers
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: build_platform != target_platform
      then:
        - qt-main
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - eigen
    - numpy
    - pip
    - python
    - qt-main
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-eigen-stl-containers
    - ros-jazzy-eigen3-cmake-module
    - ros-jazzy-geometry-msgs
    - ros-jazzy-interactive-markers
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-components
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-rviz-common
    - ros-jazzy-rviz-default-plugins
    - ros-jazzy-rviz-ogre-vendor
    - ros-jazzy-rviz-rendering
    - ros-jazzy-sensor-msgs
    - ros-jazzy-shape-msgs
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-eigen
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-trajectory-msgs
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - eigen
    - python
    - qt-main
    - ros-jazzy-ament-index-python
    - ros-jazzy-eigen-stl-containers
    - ros-jazzy-eigen3-cmake-module
    - ros-jazzy-geometry-msgs
    - ros-jazzy-interactive-markers
    - ros-jazzy-launch
    - ros-jazzy-launch-ros
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-components
    - ros-jazzy-ros-workspace
    - ros-jazzy-rviz-common
    - ros-jazzy-rviz-default-plugins
    - ros-jazzy-rviz-ogre-vendor
    - ros-jazzy-rviz-rendering
    - ros-jazzy-rviz2
    - ros-jazzy-sensor-msgs
    - ros-jazzy-shape-msgs
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-eigen
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-trajectory-msgs
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
