# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-point-cloud-transport-py
  version: 4.0.7
source:
  git: https://github.com/ros2-gbp/point_cloud_transport-release.git
  tag: release/jazzy/point_cloud_transport_py/4.0.7-1
  target_directory: ros-jazzy-point-cloud-transport-py/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  repository: https://github.com/ros-perception/point_cloud_transport
  license: BSD-3-Clause
  summary: Python API for point_cloud_transport
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: build_platform != target_platform
      then:
        - pybind11
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake-python
    - ros-jazzy-ament-cmake-ros
    - ros-jazzy-pluginlib
    - ros-jazzy-point-cloud-transport
    - ros-jazzy-pybind11-vendor
    - ros-jazzy-python-cmake-module
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-sensor-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - pybind11
  run:
    - python
    - ros-jazzy-pluginlib
    - ros-jazzy-point-cloud-transport
    - ros-jazzy-pybind11-vendor
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-workspace
    - ros-jazzy-rpyutils
    - ros-jazzy-sensor-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
