# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-warehouse-ros
  version: 2.0.5
source:
  git: https://github.com/ros2-gbp/warehouse_ros-release.git
  tag: release/jazzy/warehouse_ros/2.0.5-1
  target_directory: ros-jazzy-warehouse-ros/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://ros.org/wiki/warehouse_ros
  license: BSD-3-Clause
  summary: Persistent storage of ROS messages
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - libboost-devel
    - libboost-python-devel
    - numpy
    - openssl
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-copyright
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-geometry-msgs
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-ros
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - libboost-devel
    - libboost-python-devel
    - openssl
    - python
    - ros-jazzy-geometry-msgs
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-workspace
    - ros-jazzy-std-msgs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-ros
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
