# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-rviz-default-plugins
  version: 14.1.19
source:
  git: https://github.com/ros2-gbp/rviz-release.git
  tag: release/jazzy/rviz_default_plugins/14.1.19-1
  target_directory: ros-jazzy-rviz-default-plugins/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://github.com/ros2/rviz/blob/ros2/README.md
  repository: https://github.com/ros2/rviz
  license: BSD-3-Clause
  summary: Several default plugins for rviz to cover the basic functionality.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: build_platform != target_platform
      then:
        - qt-main
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - qt-main
    - ros-jazzy-ament-cmake-cppcheck
    - ros-jazzy-ament-cmake-cpplint
    - ros-jazzy-ament-cmake-gmock
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-cmake-lint-cmake
    - ros-jazzy-ament-cmake-ros
    - ros-jazzy-ament-cmake-uncrustify
    - ros-jazzy-ament-cmake-xmllint
    - ros-jazzy-ament-index-cpp
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-geometry-msgs
    - ros-jazzy-gz-math-vendor
    - ros-jazzy-image-transport
    - ros-jazzy-interactive-markers
    - ros-jazzy-laser-geometry
    - ros-jazzy-map-msgs
    - ros-jazzy-nav-msgs
    - ros-jazzy-pluginlib
    - ros-jazzy-point-cloud-transport
    - ros-jazzy-rclcpp
    - ros-jazzy-resource-retriever
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-rviz-common
    - ros-jazzy-rviz-ogre-vendor
    - ros-jazzy-rviz-rendering
    - ros-jazzy-rviz-rendering-tests
    - ros-jazzy-rviz-visual-testing-framework
    - ros-jazzy-tf2
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-ros
    - ros-jazzy-urdf
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - python
    - qt-main
    - ros-jazzy-geometry-msgs
    - ros-jazzy-gz-math-vendor
    - ros-jazzy-image-transport
    - ros-jazzy-interactive-markers
    - ros-jazzy-laser-geometry
    - ros-jazzy-map-msgs
    - ros-jazzy-nav-msgs
    - ros-jazzy-pluginlib
    - ros-jazzy-point-cloud-transport
    - ros-jazzy-rclcpp
    - ros-jazzy-resource-retriever
    - ros-jazzy-ros-workspace
    - ros-jazzy-rviz-common
    - ros-jazzy-rviz-ogre-vendor
    - ros-jazzy-rviz-rendering
    - ros-jazzy-tf2
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-ros
    - ros-jazzy-urdf
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
