# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-plotjuggler
  version: 3.15.0
source:
  git: https://github.com/ros2-gbp/plotjuggler-release.git
  tag: release/jazzy/plotjuggler/3.15.0-1
  target_directory: ros-jazzy-plotjuggler/src/work
  patches:
    - patch/ros-jazzy-plotjuggler.osx.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://github.com/facontidavide/PlotJuggler
  license: MPL-2.0
  summary: 'PlotJuggler: juggle with data'
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: build_platform != target_platform
      then:
        - qt-main
    - if: build_platform != target_platform
      then:
        - git-lfs
  host:
    - ${{ 'elfutils' if linux }}
    - if: build_platform == target_platform
      then:
        - pkg-config
    - cppzmq
    - fmt
    - libboost-devel
    - libboost-python-devel
    - libprotobuf
    - libxcb
    - lz4
    - nlohmann_json
    - numpy
    - pip
    - protobuf
    - python
    - qt-main
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-index-cpp
    - ros-jazzy-data-tamer-cpp
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros2-distro-mutex 0.14.* jazzy_*
    - zeromq
    - zstd
    - if: build_platform == target_platform
      then:
        - git-lfs
  run:
    - cppzmq
    - fmt
    - libboost-devel
    - libboost-python-devel
    - libprotobuf
    - lz4
    - nlohmann_json
    - protobuf
    - python
    - qt-main
    - ros-jazzy-ament-index-cpp
    - ros-jazzy-data-tamer-cpp
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-workspace
    - ros2-distro-mutex 0.14.* jazzy_*
    - zeromq
    - zstd
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
