# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-point-cloud-interfaces
  version: 4.0.3
source:
  git: https://github.com/ros2-gbp/point_cloud_transport_plugins-release.git
  tag: release/jazzy/point_cloud_interfaces/4.0.3-1
  target_directory: ros-jazzy-point-cloud-interfaces/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  repository: https://github.com/ctu-vras/draco_point_cloud_transport
  homepage: https://wiki.ros.org/draco_point_cloud_transport
  license: BSD-3-Clause
  summary: msg definitions for use with point_cloud_transport plugins.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: target_platform == 'emscripten-wasm32'
      then:
        - ros-jazzy-rosidl-default-generators
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-default-generators
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - python
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-default-runtime
    - ros-jazzy-sensor-msgs
    - ros-jazzy-std-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
