# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros2-apriltag
  version: 3.4.5

build:
  number: 25
  script: ''
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://april.eecs.umich.edu/software/apriltag.html
  repository: https://github.com/AprilRobotics/apriltag
  license: BSD-3-Clause
  summary: AprilTag detector library
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build: []
  host:
    - libgl-devel
    - libopencv
    - libopengl-devel
    - numpy
    - py-opencv
    - python
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-ros-environment
    - ros2-ros-workspace
  run:
    - apriltag >=3.4.5, <3.4.6a0
    - python
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-ros-workspace
