# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-rsl
  version: 1.2.0
source:
  git: https://github.com/ros2-gbp/RSL-release.git
  tag: release/jazzy/rsl/1.2.0-1
  target_directory: ros-jazzy-rsl/src/work

build:
  script: ${{ '$RECIPE_DIR/build_catkin.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_catkin.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: BSD-3-Clause
  summary: ROS Support Library
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: build_platform != target_platform
      then:
        - git
    - if: build_platform != target_platform
      then:
        - doxygen
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - clang-tools
    - eigen
    - fmt
    - graphviz
    - numpy
    - pip
    - python
    - range-v3
    - ros-jazzy-ament-cmake-ros
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-tcb-span
    - ros-jazzy-tl-expected
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: build_platform == target_platform
      then:
        - git
    - if: build_platform == target_platform
      then:
        - doxygen
  run:
    - eigen
    - fmt
    - python
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-workspace
    - ros-jazzy-tcb-span
    - ros-jazzy-tl-expected
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
