# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-ur-description
  version: 3.5.0
source:
  git: https://github.com/ros2-gbp/ur_description-release.git
  tag: release/jazzy/ur_description/3.5.0-1
  target_directory: ros-jazzy-ur-description/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 17
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  repository: https://github.com/UniversalRobots/Universal_Robots_ROS2_Description
  license: BSD-3-Clause OR LicenseRef-Universal-Robots-A-S--Terms-and-Conditions-for-Use-of-Graphical-Documentation
  summary: URDF description for Universal Robots
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-pytest
    - ros-jazzy-launch-testing-ament-cmake
    - ros-jazzy-launch-testing-ros
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-xacro
    - ros2-distro-mutex 0.14.* jazzy_*
    - urdfdom
  run:
    - python
    - ros-jazzy-joint-state-publisher-gui
    - ros-jazzy-launch
    - ros-jazzy-launch-ros
    - ros-jazzy-robot-state-publisher
    - ros-jazzy-ros-workspace
    - ros-jazzy-rviz2
    - ros-jazzy-urdf
    - ros-jazzy-xacro
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
