# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-plotjuggler-ros
  version: 2.3.1
source:
  git: https://github.com/ros2-gbp/plotjuggler-ros-plugins-release.git
  tag: release/jazzy/plotjuggler_ros/2.3.1-1
  target_directory: ros-jazzy-plotjuggler-ros/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://github.com/facontidavide/PlotJuggler
  license: AGPL-3.0-only
  summary: PlotJuggler plugin for ROS
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: build_platform != target_platform
      then:
        - qt-main
  host:
    - ${{ 'libgl-devel' if linux }}
    - ${{ 'libopengl-devel' if linux }}
    - if: build_platform == target_platform
      then:
        - pkg-config
    - fmt
    - libboost-devel
    - libboost-python-devel
    - numpy
    - pip
    - python
    - qt-main
    - ros-jazzy-ament-cmake
    - ros-jazzy-plotjuggler
    - ros-jazzy-plotjuggler-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-rcpputils
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosbag2-transport
    - ros-jazzy-tf2-msgs
    - ros-jazzy-tf2-ros
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - fmt
    - libboost-devel
    - libboost-python-devel
    - python
    - qt-main
    - ros-jazzy-plotjuggler
    - ros-jazzy-plotjuggler-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-rcpputils
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosbag2-transport
    - ros-jazzy-tf2-msgs
    - ros-jazzy-tf2-ros
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
