# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-tf2
  version: 0.36.19
source:
  git: https://github.com/ros2-gbp/geometry2-release.git
  tag: release/jazzy/tf2/0.36.19-1
  target_directory: ros-jazzy-tf2/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://www.ros.org/wiki/tf2
  license: BSD-3-Clause
  summary: tf2 is the second generation of the transform library, which lets the user keep track of multiple coordinate frames over time. tf2 maintains the relationship between coordinate frames in a tree structure buffered in time, and lets the user transform points, vectors, etc between any two coordinate frames at any desired point in time.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-copyright
    - ros-jazzy-ament-cmake-cppcheck
    - ros-jazzy-ament-cmake-cpplint
    - ros-jazzy-ament-cmake-google-benchmark
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-cmake-lint-cmake
    - ros-jazzy-ament-cmake-ros
    - ros-jazzy-ament-cmake-uncrustify
    - ros-jazzy-ament-cmake-xmllint
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-geometry-msgs
    - ros-jazzy-rcutils
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-runtime-cpp
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - python
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-geometry-msgs
    - ros-jazzy-rcutils
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosidl-runtime-cpp
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
