#!/usr/bin/env bash

# PLEASE NOTE: This script has been automatically generated by conda-smithy. Any changes here
# will be lost next time ``conda smithy rerender`` is run. If you would like to make permanent
# changes to this script, consider a proposal to conda-smithy so that other feedstocks can also
# benefit from the improvement.

set -xeuo pipefail
export PYTHONUNBUFFERED=1
export FEEDSTOCK_ROOT="${FEEDSTOCK_ROOT:-/home/conda/feedstock_root}"
export RECIPE_ROOT="${RECIPE_ROOT:-/home/conda/recipe_root}"

curl -fsSL https://pixi.sh/install.sh | bash
export PATH="$HOME/.pixi/bin:$PATH"

export CONDA_BLD_PATH="/opt/conda/build_artifacts"

pwd

for recipe in ${CURRENT_RECIPES[@]}; do
	cd ${FEEDSTOCK_ROOT}/recipes/${recipe}
	pixi run rattler-build build --recipe . \
		-m ${FEEDSTOCK_ROOT}/.ci_support/conda_forge_pinnings.yaml \
		-m ${FEEDSTOCK_ROOT}/conda_build_config.yaml \
		-c robostack-jazzy -c conda-forge \
		--output-dir $CONDA_BLD_PATH
done

anaconda -t ${ANACONDA_API_TOKEN} upload /opt/conda/build_artifacts/linux-*/*.conda --force