# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros2-rosidl-core-generators
  version: 0.2.1
source:
  git: https://github.com/ros2-gbp/rosidl_core-release.git
  tag: release/jazzy/rosidl_core_generators/0.2.1-1
  target_directory: ros2-rosidl-core-generators/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 25
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  repository: https://github.com/ros2/rosidl_core
  license: Apache-2.0
  summary: A configuration package defining core ROS interface generators.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: osx
      then:
        - clang-tools ${{ (cxx_compiler_version ~ '.*') if cxx_compiler_version is defined else '*' }}
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros2-ament-cmake
    - ros2-ament-cmake-core
    - ros2-ament-lint-auto
    - ros2-ament-lint-common
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-ros-environment
    - ros2-ros-workspace
    - ros2-rosidl-cmake
    - ros2-rosidl-generator-c
    - ros2-rosidl-generator-cpp
    - ros2-rosidl-generator-py
    - ros2-rosidl-generator-rs
    - ros2-rosidl-generator-type-description
    - ros2-rosidl-typesupport-c
    - ros2-rosidl-typesupport-cpp
    - ros2-rosidl-typesupport-fastrtps-c
    - ros2-rosidl-typesupport-fastrtps-cpp
    - ros2-rosidl-typesupport-introspection-c
    - ros2-rosidl-typesupport-introspection-cpp
  run:
    - python
    - ros2-ament-cmake-core
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-ros-workspace
    - ros2-rosidl-cmake
    - ros2-rosidl-generator-c
    - ros2-rosidl-generator-cpp
    - ros2-rosidl-generator-py
    - ros2-rosidl-generator-rs
    - ros2-rosidl-generator-type-description
    - ros2-rosidl-typesupport-c
    - ros2-rosidl-typesupport-cpp
    - ros2-rosidl-typesupport-fastrtps-c
    - ros2-rosidl-typesupport-fastrtps-cpp
    - ros2-rosidl-typesupport-introspection-c
    - ros2-rosidl-typesupport-introspection-cpp
