# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros2-visp
  version: 3.7.0

build:
  number: 25
  script: ''
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://visp.inria.fr
  repository: https://github.com/lagadic/visp
  license: GPL-2.0-or-later
  summary: ViSP standing for Visual Servoing Platform is a modular cross platform library that allows prototyping and developing applications using visual tracking and visual servoing technics at the heart of the researches done by Inria Lagadic team. ViSP is able to compute control laws that can be applied to robotic systems. It provides a set of visual features that can be tracked using real time image processing or computer vision algorithms. ViSP provides also simulation capabilities. ViSP can be useful in robotics, computer vision, augmented reality and computer animation.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - doxygen
  host:
    - bzip2
    - eigen
    - eigen-abi-devel
    - graphviz
    - gsl
    - libblas
    - libjpeg-turbo
    - liblapack
    - libopencv
    - libpng
    - libxml2
    - nlohmann_json
    - py-opencv
    - python
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-ros-environment
    - ros2-ros-workspace
    - xorg-libx11
    - xorg-xorgproto
    - if: build_platform == target_platform
      then:
        - doxygen
  run:
    - bzip2
    - eigen
    - eigen-abi-devel
    - gsl
    - libblas
    - libjpeg-turbo
    - liblapack
    - libopencv
    - libpng
    - libxml2
    - nlohmann_json
    - py-opencv
    - python
    - ros2-distro-mutex 0.19.* jazzy_*
    - ros2-ros-workspace
    - visp >=3.7.0, <3.8.0a0
    - xorg-libx11
    - xorg-xorgproto
