# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-rosbag2-py
  version: 0.26.9
source:
  git: https://github.com/ros2-gbp/rosbag2-release.git
  tag: release/jazzy/rosbag2_py/0.26.9-1
  target_directory: ros-jazzy-rosbag2-py/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: Apache-2.0
  summary: Python API for rosbag2
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: build_platform != target_platform
      then:
        - pybind11
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - pytest
    - python
    - ros-jazzy-ament-cmake-python
    - ros-jazzy-ament-cmake-ros
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-pybind11-vendor
    - ros-jazzy-python-cmake-module
    - ros-jazzy-rcl-interfaces
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosbag2-compression
    - ros-jazzy-rosbag2-compression-zstd
    - ros-jazzy-rosbag2-cpp
    - ros-jazzy-rosbag2-storage
    - ros-jazzy-rosbag2-storage-default-plugins
    - ros-jazzy-rosbag2-test-common
    - ros-jazzy-rosbag2-test-msgdefs
    - ros-jazzy-rosbag2-transport
    - ros-jazzy-rosidl-runtime-py
    - ros-jazzy-std-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - pybind11
  run:
    - python
    - ros-jazzy-pybind11-vendor
    - ros-jazzy-rclpy
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosbag2-compression
    - ros-jazzy-rosbag2-cpp
    - ros-jazzy-rosbag2-storage
    - ros-jazzy-rosbag2-transport
    - ros-jazzy-rpyutils
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
