# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-web-video-server
  version: 3.0.0
source:
  git: https://github.com/ros2-gbp/web_video_server-release.git
  tag: release/jazzy/web_video_server/3.0.0-1
  target_directory: ros-jazzy-web-video-server/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 16
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://ros.org/wiki/web_video_server
  repository: https://github.com/RobotWebTools/web_video_server
  license: BSD-3-Clause
  summary: HTTP Streaming of ROS Image Topics in Multiple Formats
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - ffmpeg
    - libboost-devel
    - libboost-python-devel
    - libopencv
    - numpy
    - pip
    - pkg-config
    - py-opencv
    - python
    - ros-jazzy-ament-cmake-clang-tidy
    - ros-jazzy-ament-cmake-copyright
    - ros-jazzy-ament-cmake-lint-cmake
    - ros-jazzy-ament-cmake-ros
    - ros-jazzy-ament-cmake-uncrustify
    - ros-jazzy-ament-cmake-xmllint
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-async-web-server-cpp
    - ros-jazzy-cv-bridge
    - ros-jazzy-image-transport
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-components
    - ros-jazzy-rmw
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-sensor-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
  run:
    - ffmpeg
    - libboost-devel
    - libboost-python-devel
    - libopencv
    - py-opencv
    - python
    - ros-jazzy-async-web-server-cpp
    - ros-jazzy-cv-bridge
    - ros-jazzy-image-transport
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-components
    - ros-jazzy-rmw
    - ros-jazzy-ros-workspace
    - ros-jazzy-sensor-msgs
    - ros2-distro-mutex 0.14.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
